# # Define required macros here
# SHELL = /bin/sh

# CC = g++


# compile:
# 	${CC} homework_1.cpp -o homework_1

# clean:
# 	rm homework_1

# Define required macros here
SHELL = /bin/sh

CC = g++


compile:
	${CC} homework_1.cpp -o homework_1

clean:
	rm homework_1

